{% set name = "libdispatch" %}
{% set version = "6.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/apple/swift-corelibs-libdispatch/archive/refs/tags/swift-{{ version }}-RELEASE.tar.gz
  sha256: 150066ba341e49b8518a0b879ba82941d6d8734ab37cb76683f2a155369e5030
  patches:
    - 0001-glibc-unistd-wrapper.patch  # [linux]

build:
  number: 0
  skip: true  # [osx]
  run_exports:
    - {{ pin_subpackage(name) }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - lld  # [win]
    - {{ stdlib("c") }}
    - cmake
    - ninja

test:
  commands:
    - test -f $PREFIX/lib/libdispatch${SHLIB_EXT}  # [not win]
    - if not exist %LIBRARY_LIB%\\dispatch.lib exit 1  # [win]
    - test -f $PREFIX/include/dispatch/unistd.h  # [linux]

about:
  home: https://github.com/apple/swift-corelibs-libdispatch
  license: Apache-2.0
  license_file: LICENSE
  summary: 'Comprehensive support for concurrent code execution on multicore hardware'
  description: 'The libdispatch Project, (a.k.a. Grand Central Dispatch), for concurrency on multicore hardware'
  doc_url: https://apple.github.io/swift-corelibs-libdispatch
  dev_url: https://github.com/apple/swift-corelibs-libdispatch

extra:
  recipe-maintainers:
    - chawyehsu
